services:
  frontend:
    image: wasabilazybumai/riasec-frontend:latest
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: riasec_frontend
    ports:
      - "8080:8080"
    depends_on:
      - backend
      - redis
    restart: unless-stopped

  backend:
    image: wasabilazybumai/riasec-backend:latest
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: riasec_backend
    ports:
      - "8000:80"
    depends_on:
      - db
    volumes:
      - ./backend:/var/www/html
    environment:
      - DB_HOST=db
      - DB_NAME=riasec_db
      - DB_USER=riasec_user
      - DB_PASS=riasec_password
      - APP_URL=${APP_URL:-https://coursealign-app-c5wcx.ondigitalocean.app/#/login}
      - SMTP_HOST=${SMTP_HOST:-smtp.gmail.com}
      - SMTP_USER=${SMTP_USER:-your_email@gmail.com}
      - SMTP_PASS=${SMTP_PASS:-your_app_password}
      - SMTP_PORT=${SMTP_PORT:-587}
      - SMTP_SECURE=${SMTP_SECURE:-tls}
    restart: unless-stopped

  db:
    image: mysql:8.0
    container_name: riasec_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: riasec_db
      MYSQL_USER: riasec_user
      MYSQL_PASSWORD: riasec_password
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./assets/riasec_db.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:alpine
    container_name: riasec_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: riasec_phpmyadmin
    restart: unless-stopped
    ports:
      - "8081:80"
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_USER=riasec_user
      - PMA_PASSWORD=riasec_password
    depends_on:
      - db

volumes:
  redis_data:
    name: riasec_redis_data
  db_data:
    name: riasec_db_data
